import './globals.css'

// Components
import Header from '@/components/headers/header'
import Footer from '@/components/footers/footer'

export const metadata = {
  title: 'ThermoEngineer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}
