import './globals.css';

// Components
import Header from '@/components/headers/header';
import Footer from '@/components/footers/footer';

// Fonts
import { montserrat } from './fonts';

export const metadata = {
  title: 'Thermoengineer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body className='font-monts'>
        <header >
          <Header />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}
